# Generated by Django 5.1.2 on 2024-12-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
                ('shop_type', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Review', 'Under Review')], default='Active', max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
    ]
