# Generated by Django 5.1.2 on 2024-12-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTrendsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('trend_data', models.JSONField()),
                ('fetched_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.IntegerField()),
                ('competition_level', models.CharField(max_length=50)),
                ('suggested_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255)),
                ('competitor', models.CharField(max_length=255)),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('findings', models.TextField()),
            ],
        ),
    ]
