# Generated by Django 5.1.2 on 2024-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('target_keywords', models.CharField(max_length=255)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('anchor_text', models.CharField(max_length=255)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('domain_authority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SEOReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('report_date', models.DateField(auto_now_add=True)),
                ('organic_traffic', models.IntegerField()),
                ('bounce_rate', models.FloatField()),
                ('backlinks_count', models.IntegerField()),
                ('keyword_rankings', models.JSONField()),
            ],
        ),
    ]
